---
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
skip_tags: true
branches:
  only:
    - master
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
before_build:
  - nuget update -self
  - nuget restore
test_script:
  - ps: Switch-DockerLinux
  - dotnet test .\ResultTests\ResultTests.csproj --no-build
configuration: Release
image: "Windows Server 2019"
nuget:
  disable_publish_on_pr: true
cache:
  - '%USERPROFILE%\.nuget\packages'
environment:
  AppVeyorAPIToken:
    secure: GvygCCndEp8eiXvItooIyglWYnyfUvg4YNyaufw3N3A=
version: "0.2.1.{build}"